import type { Lang, Verdict } from "@/game/types";

export const strings = {
  es: {
    fileNo: "Expediente",
    open: "Abrir expediente",
    resume: "Continuar",
    restart: "Empezar de nuevo",
    restartConfirm: "¿Descartar este interrogatorio y empezar de nuevo?",
    questionsLeft: "Preguntas",
    clock: "Hora",
    suspects: "Implicados",
    evidence: "Pruebas",
    newEvidence: "Nueva",
    age: "años",
    placeholder: "Escriba su pregunta…",
    ask: "Preguntar",
    present: "Mostrar prueba",
    presentTo: (name: string) => `Mostrar a ${name}`,
    presentNote: "Puede acompañarla con una pregunta.",
    cancel: "Cancelar",
    close: "Cerrar",
    detective: "DET.",
    waiting: "…",
    added: (title: string) => `Se agrega al expediente: ${title}`,
    showed: (title: string) => `[Muestra: ${title}]`,
    emptyTranscript: (name: string) => `Sin declaraciones de ${name} todavía.`,
    accuse: "Acusar",
    accuseTitle: "Acusación formal",
    accuseWho: "¿Quién se llevó la corona?",
    accuseCite: (n: number) => `Cite hasta ${n} pruebas que lo demuestren.`,
    accuseConfirm: "Presentar acusación",
    accuseForced: "Se acabaron las preguntas. La procesión está por salir: tiene que acusar a alguien.",
    verdict: { solved: "Caso resuelto", weak: "Caso sin pruebas", wrong: "Acusación equivocada" } satisfies Record<Verdict, string>,
    playAgain: "Jugar otra vez",
    errors: {
      closed: "Archivo cerrado por hoy. El servicio gratuito llegó a su límite diario. Vuelva mañana, detective.",
      busy: "Hay otros detectives en la casa cural. Espere un minuto y vuelva a preguntar.",
      limit: "Por hoy ya hizo todas las preguntas que el archivo permite. Vuelva mañana, detective.",
      generic: "La declaración no quedó registrada. Intente otra vez.",
    },
    lang: "English",
    agency: "Fiscalía Regional",
    dateStamp: "22 may",
    record: "Acta de declaración",
    folio: "Folio",
    field: { name: "Nombre", age: "Edad", job: "Ocupación", notes: "Observaciones", print: "Índice der.", statements: "Declaraciones" },
    changedStory: "cambió su versión",
    left: (n: number) => `quedan ${n}`,
    kind: { report: "Documento", program: "Impreso", statement: "Declaración", photos: "Fotografías", messages: "Mensajes" },
    contactSheet: "Hoja de contactos",
    accuseRecord: "Acta de acusación",
    sound: { on: "Sonido: sí", off: "Sonido: no" },
    dropHint: (name: string) => `Suéltela aquí para mostrársela a ${name}`,
    memo: {
      title: "Memorándum",
      fields: [
        ["Para", "El detective asignado"],
        ["De", "Fiscalía Regional"],
        ["Fecha", "22 de mayo, 7:38 a. m."],
        ["Asunto", "Robo de la corona de Santa Rita. Cómo proceder."],
      ],
      points: [
        {
          head: "Interrogue.",
          body: "Elija a una persona en las pestañas del fólder y pregúntele lo que quiera, con sus palabras. Cada pregunta toma tres minutos. Tiene 24 antes de que salga la procesión.",
        },
        { head: "No les crea.", body: "Los tres ocultan algo. Compare lo que dicen con las pruebas." },
      ],
      evidence: {
        head: "Ponga las pruebas sobre la mesa.",
        drag: "Arrastre una prueba al fólder, o use «Mostrar prueba».",
        pick: "Use «Mostrar prueba» debajo de su pregunta.",
        effect: "La prueba correcta frente a la persona correcta rompe su versión, y a veces aparecen pruebas nuevas.",
      },
      last: {
        head: "Acuse con pruebas.",
        before: "Cuando esté seguro, presione ACUSAR, señale a quien se llevó la corona y cite hasta tres pruebas. Tiene que demostrar ",
        key: "el medio, el motivo y la oportunidad",
        after: ". Una sospecha no basta.",
      },
      signed: "El Fiscal Regional",
      ok: "Enterado",
      stamp: "Enterado",
      reopen: "Instrucciones",
    },
  },
  en: {
    fileNo: "Case file",
    open: "Open the file",
    resume: "Continue",
    restart: "Start over",
    restartConfirm: "Discard this interrogation and start over?",
    questionsLeft: "Questions",
    clock: "Time",
    suspects: "Persons of interest",
    evidence: "Evidence",
    newEvidence: "New",
    age: "years old",
    placeholder: "Type your question…",
    ask: "Ask",
    present: "Show evidence",
    presentTo: (name: string) => `Show to ${name}`,
    presentNote: "You can add a question with it.",
    cancel: "Cancel",
    close: "Close",
    detective: "DET.",
    waiting: "…",
    added: (title: string) => `Added to the file: ${title}`,
    showed: (title: string) => `[Shows: ${title}]`,
    emptyTranscript: (name: string) => `No statements from ${name} yet.`,
    accuse: "Accuse",
    accuseTitle: "Formal accusation",
    accuseWho: "Who took the crown?",
    accuseCite: (n: number) => `Cite up to ${n} pieces of evidence that prove it.`,
    accuseConfirm: "Make the accusation",
    accuseForced: "You're out of questions. The procession is about to leave: you have to accuse someone.",
    verdict: { solved: "Case closed", weak: "No case", wrong: "Wrong person" } satisfies Record<Verdict, string>,
    playAgain: "Play again",
    errors: {
      closed: "The archive is closed for today. The free service hit its daily limit. Come back tomorrow, detective.",
      busy: "Other detectives are in the rectory. Wait a minute and ask again.",
      limit: "You've asked all the questions the archive allows for today. Come back tomorrow, detective.",
      generic: "The statement wasn't recorded. Try again.",
    },
    lang: "Español",
    agency: "Regional Prosecutor's Office",
    dateStamp: "May 22",
    record: "Statement record",
    folio: "Page",
    field: { name: "Name", age: "Age", job: "Occupation", notes: "Notes", print: "R. index", statements: "Statements" },
    changedStory: "changed the story",
    left: (n: number) => `${n} left`,
    kind: { report: "Document", program: "Printed program", statement: "Statement", photos: "Photographs", messages: "Messages" },
    contactSheet: "Contact sheet",
    accuseRecord: "Accusation record",
    sound: { on: "Sound: on", off: "Sound: off" },
    dropHint: (name: string) => `Drop it here to show ${name}`,
    memo: {
      title: "Memorandum",
      fields: [
        ["To", "The assigned detective"],
        ["From", "Regional Prosecutor's Office"],
        ["Date", "May 22, 7:38 a.m."],
        ["Subject", "Theft of the Santa Rita crown. How to proceed."],
      ],
      points: [
        {
          head: "Question them.",
          body: "Pick a person from the folder tabs and ask whatever you want, in your own words. Each question takes three minutes. You have 24 before the procession leaves.",
        },
        { head: "Don't believe them.", body: "All three are hiding something. Check what they say against the evidence." },
      ],
      evidence: {
        head: "Put the evidence on the table.",
        drag: "Drag a document onto the folder, or use “Show evidence.”",
        pick: "Use “Show evidence” under your question.",
        effect: "The right document in front of the right person breaks their story, and sometimes new evidence turns up.",
      },
      last: {
        head: "Accuse with proof.",
        before: "When you're sure, press ACCUSE, name who took the crown and cite up to three pieces of evidence. You have to prove ",
        key: "means, motive and opportunity",
        after: ". A hunch is not enough.",
      },
      signed: "Regional Prosecutor",
      ok: "Understood",
      stamp: "Noted",
      reopen: "Instructions",
    },
  },
} as const satisfies Record<Lang, unknown>;

export type Strings = (typeof strings)[Lang];

/** In-game clock: the file opens at 7:40 and each question takes three minutes. */
export function clockAt(questionsUsed: number): string {
  const minutes = 7 * 60 + 40 + questionsUsed * 3;
  return `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`;
}
